"""primeira migration

Revision ID: 3ba49294a9ca
Revises: 
Create Date: 2022-10-18 17:22:46.485320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba49294a9ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produto', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'usuario_id')
    # ### end Alembic commands ###
