"""tabela usuario e relacionamentos

Revision ID: 5459d0ce9f0f
Revises: 39b718d611c0
Create Date: 2022-10-17 16:31:42.097827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5459d0ce9f0f'
down_revision = '39b718d611c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pedido', 'usuario', ['usuario_id'], ['id'])
    op.add_column('produto', sa.Column('pedido_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produto', 'pedido', ['pedido_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'pedido_id')
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.drop_column('pedido', 'usuario_id')
    # ### end Alembic commands ###
