"""delecao de produto em cascata

Revision ID: 5b8c9335ca92
Revises: 3ba49294a9ca
Create Date: 2022-10-18 17:32:37.880277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8c9335ca92'
down_revision = '3ba49294a9ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'produto', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto', type_='foreignkey')
    # ### end Alembic commands ###
